services:
  application:
    build: .
    container_name: app
    environment:
      CONN_STRING: ${CONN_STRING}
      DB_HOST: database
    ports:
      - "9111:9111"
    depends_on:
      - database

  database:
    image: postgres:18-bookworm
    container_name: db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql

volumes:
  pgdata: